name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed
  push:
    branches:
      - main
      - develop

jobs:
  test-and-publish:
    name: Test and Publish Pact
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (for Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run tests and generate Pact contract
      - name: Run tests
        run: ./gradlew clean test

      # Publish Pact to Pact Broker
      - name: Publish Pact to Pact Broker
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          docker run --rm \
            -v $PWD:$PWD \
            -w $PWD \
            -e PACT_BROKER_BASE_URL=$PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN=$PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest publish build/pacts --consumer-app-version $GITHUB_SHA --branch $BRANCH_NAME

  delete-pactflow-branch:
    name: Delete Incoming PactFlow Branch
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Delete PactFlow branch
      - name: Delete Incoming PactFlow Branch
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          echo "Deleting incoming branch on PactFlow: $INCOMING_BRANCH"
          docker run --rm \
            -v $PWD:$PWD \
            -w $PWD \
            -e PACT_BROKER_BASE_URL=$PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN=$PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest broker delete-branch \
            --pacticipant pactflow-consumer \
            --branch $INCOMING_BRANCH
